global:
  scrape_interval: 15s #

scrape_configs:
  # FastAPI
  - job_name: 'fastapi-backend'
    metrics_path: '/metrics'
    static_configs:
      # public IP
      - targets: ['10.0.11.17:8000']

  # mysql
  - job_name: 'rds-mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'rds-mysql-replica'
    static_configs:
      - targets: [ 'mysqld-exporter-replica:9104' ]